version: "3"

services:
    laravel_sample_crud_web:
        build: .
        volumes:
            - ./src:/src
        command: /sbin/init -c "nginx && systemctl start php-fpm && tail -f /dev/null"
        # command: /sbin/init -c "tail -f /dev/null"
        ports:
            - "8000:8000"
        links:
            - laravel_sample_crud_db
        privileged: true

    laravel_sample_crud_db:
      image: mysql:5.7
      volumes:
          - laravel_sample_crud_db_data
      ports:
             - "3306:3306"
      environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: laravel_db
        MYSQL_USER: default
        MYSQL_PASSWORD: secret
      privileged: true

    laravel_sample_crud_db_data:
        image: busybox
        volumes:
            - /var/lib/mysql
        command: sh
