version: "3"

services:
    web:
        image: centos:okamok-laravel
        volumes:
            - ./src:/src
        # nginxとかも systemctl start nginx とかになる。
        command: /sbin/init -c "systemctl start mysqld && cd /src/Sample && php artisan serve --host=0.0.0.0 --port=80 && tail -f /dev/null"

        # nginxとかをインストールしたらこっちで
        # command: /sbin/init -c "systemctl start mysqld && systemctl start nginx && systemctl start php-fpm && tail -f /dev/null"


        # command: /sbin/init -c "tail -f /dev/null"
        ports:
            - "80:80"
            - "3306:3306"
        # links:
        #     - db
        privileged: true

    # db:
    #   image: mysql:5.7
    #   volumes:
    #       - db_data
    #   ports:
    #          - "3306:3306"
    #   environment:
    #     MYSQL_ROOT_PASSWORD: password
    #     MYSQL_DATABASE: laravel_db
    #     MYSQL_USER: okamura
    #     MYSQL_PASSWORD: okamura
    #   privileged: true
    #
    # db_data:
    #     image: busybox
    #     volumes:
    #         - /var/lib/mysql
    #     command: sh
